apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-test-dbtdag
spec:
  template:
    spec:
      containers:
        - name: dbt
          image: benchmark:0.0.3
          env:
            - name: USE_COSMOS_DBT_DAG
              value: "1"
          command: ["airflow", "dags", "test", "example_dbt_dag"]
          resources:
            # Equivalent to A10 instance
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      restartPolicy: Never
  backoffLimit: 0
