altered_jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: astronomer-dag-authoring
      dataset: cosmos_async_bechmark_test
      threads: 4 # Must be a value of 1 or greater
      keyfile: # /PATH/TO/BIGQUERY/keyfile.json
