fhir_dbt_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: astronomer-dag-authoring
      dataset: release_17 # You can also use "schema" here
      threads: 4 # Must be a value of 1 or greater
      keyfile: "{{ env_var('KEY_PATH', '/app/key.json') }}"
